version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - 5860:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - budget
      - tache

  budget:
    build: Budget/
    depends_on:
      - mariadb
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  tache:
    build: taches_python/
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    volumes:
       - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: domestique
      MYSQL_USER: root

volumes:
  data: